version: '3'

services:
  metaplex:
    build: .
    container_name: gazelplex
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: store.cerebrumsti.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: store.cerebrumsti.com
      LETSENCRYPT_EMAIL: alp@cerebrumtechnologies.com

networks:
    default:
       external:
         name: proxy
